source 'https://rubygems.org'

gem 'jekyll'
gem "github-pages", "~> 231", group: :jekyll_plugins

gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-coffeescript"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-seo"
gem "jemoji"

