source 'https://rubygems.org'

gem 'jekyll'
gem "github-pages", "~> GITHUB-PAGES-VERSION", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jemoji"
end
